name: 'C++ IP_filter'


on:
  push:
    branches:
      - main
      - feature/github_actions
    paths:
      - '02.IP_filter/**'
  workflow_dispatch:

# defaults:
#   run:
#     working-directory: ./01.CICD/

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      ### Install requirements ###
      - name: Install requirements
        working-directory: ./02.IP_filter/
        run: |
             sudo apt-get update && sudo apt-get install cmake libgtest-dev google-mock -y 
             cd /usr/src/googletest
             sudo cmake .
             sudo cmake --build . --target install
      ### Build ###
      - name: Build 02.IP_filter
        working-directory: ./02.IP_filter/
        run: |
             cmake -B build
             cmake --build build
             cmake --build build --target test
             ls -la build/Debug
      ### Run tests ###
      - name: Run GTest
        working-directory: ./02.IP_filter/
        run: |
             build/Debug/ip_filter_test.test
      ### Check hashsum ###
      - name: Check hashsum
        working-directory: ./02.IP_filter/
        run: |
             build/Debug/ip_filter ip_filter.tsv | md5sum


